stages:
#   download:
#     cmd: python ./stages/01_download.py
#     deps:
#       - ./stages/01_download.py
#     outs:
#       - cache

  build:
    cmd: python ./stages/02_process.py
    deps:
      - ./stages/02_process.py
      - cache
    outs:
      - brick