stages:
  download:
    cmd: ./stages/download.sh
    deps:
      - ./stages/download.sh
    outs:
      - data

  build:
    cmd: python ./stages/build.py
    deps:
      - ./stages/build.py
      - data
    outs:
      - brick